[colors.primary]
background = "#080608"
foreground = "#C2AE93"

[colors.cursor]
text = "#100C10"
cursor = "#C49A36"

[colors.selection]
background = "#362C38"
text = "#C2AE93"

[colors.normal]
black = "#362C38"
red = "#B83E46"
green = "#729B59"
yellow = "#DCAE3D"
blue = "#5C84A3"
magenta = "#7C5796"
cyan = "#48A89F"
white = "#C2AE93"

[colors.bright]
black = "#362C38"
red = "#B83E46"
green = "#729B59"
yellow = "#DCAE3D"
blue = "#5C84A3"
magenta = "#7C5796"
cyan = "#48A89F"
white = "#C2AE93"
