accent = "#DCAE3D"
cursor = "#DCAE3D"
foreground = "#C2AE93"
background = "#080608"
selection_foreground = "#C2AE93"
selection_background = "#362C38"

color0 = "#362C38"
color1 = "#B83E46"
color2 = "#729B59"
color3 = "#DCAE3D"
color4 = "#5C84A3"
color5 = "#7C5796"
color6 = "#48A89F"
color7 = "#C2AE93"
color8 = "#362C38"
color9 = "#B83E46"
color10 = "#729B59"
color11 = "#DCAE3D"
color12 = "#5C84A3"
color13 = "#7C5796"
color14 = "#48A89F"
color15 = "#C2AE93"
