background = #080608
foreground = #C2AE93
selection-background = #362C38
selection-foreground = #C2AE93
cursor-color = #DCAE3D

palette = 0=#362C38
palette = 1=#B83E46
palette = 2=#729B59
palette = 3=#DCAE3D
palette = 4=#5C84A3
palette = 5=#7C5796
palette = 6=#48A89F
palette = 7=#C2AE93

palette = 8=#362C38
palette = 9=#B83E46
palette = 10=#729B59
palette = 11=#DCAE3D
palette = 12=#5C84A3
palette = 13=#7C5796
palette = 14=#48A89F
palette = 15=#C2AE93
