$color = rgba(12, 12, 12, 1.0) # darkness_6 - Matthew 27:45
$inner_color = rgba(12, 12, 12, 1.0) # darkness_6 - Matthew 27:45
$outer_color = rgba(220, 174, 61, 1.0) # royal_sash_1 - Revelation 1:13
$font_color = rgba(194, 174, 147, 1.0) # broken_bread_1 - Matthew 26:17,26
$check_color = rgba(131, 143, 70, 1.0) # gethsemane_1 - Exodus 27:20; Matthew 26:36
